### ISSUE TITLE
addInjectStreamUrl() results in INJECT_STREAM_STATUS_START_TIMEDOUT

### ISSUE THREAD

**Issue by leovin** [AgoraIO/Advanced-Interactive-Broadcasting#12]
Windows/Android examples of "Live-Streaming-Injection" result in "INJECT_STREAM_STATUS_START_TIMEDOUT 3: Import external video stream timeout".

Using default stream injection url from Android example - "http://220.194.237.28:8000/flv/live.flv".

**Comment by guohai** [comment]
Hi @leovin 
Did you contact sales@agora.io to ensure that CDN streaming is enabled?

**Comment by leovin** [comment]
Hi @guohai 

Not yet.
Documentation gives impression that CDN streaming is optional:
"
Working Principles
- The host in a live broadcast channel pulls an online media stream, pushes it to the Agora SD-RTN and live broadcast channel through the Video Inject Server. The host and the audience in the channel can hear/see the media stream.
- If the host enabled CDN streaming, the injected media stream is also pushed to the CDN so that the CDN audience can hear/see the media stream.
"

CDN streaming is required for stream injection to work?

**Comment by guohai** [comment]
Did you make it work finally? @leovin

**Comment by leovin** [comment]
yes, thank you

**Comment by arundroid94** [comment]
@leovin

What was the solution for this error?

**Comment by leovin** [comment]
ask Agora support to enable CDN streaming for your acc on their side)

**Comment by leovin** [comment]
ask Agora support to enable CDN streaming for your acc on their side)

**Comment by arundroid94** [comment]
@leovin Thanks
