### ISSUE TITLE
onJoinChannelSuccess vs. onUserJoined for multiple user interactive broadcast (Android)

### ISSUE THREAD

**Issue by AxesandGrinds** [AgoraIO/Advanced-Interactive-Broadcasting#32]
I have some questions regarding these two functions in the file, "VideoActivity."

        @Override
        public void onJoinChannelSuccess(String channel, final int uid, int elapsed) {
            super.onJoinChannelSuccess(channel, uid, elapsed);
            sendMsg("-->onJoinChannelSuccess<--" + channel + "  -->uid<--" + uid);
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    mBigUserId = uid;

                    UserInfo mUI = new UserInfo();
                    mUI.view = mBigView;
                    mUI.uid = mBigUserId;
                    mUI.view.setZOrderOnTop(true);
                    mUserInfo.put(mBigUserId, mUI);
                }
            });
        }

        @Override
        public void onUserJoined(final int uid, int elapsed) {
            super.onUserJoined(uid, elapsed);
            sendMsg("-->onUserJoined<--" + uid);
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    UserInfo mUI = new UserInfo();
                    mUI.view = RtcEngine.CreateRendererView(VideoActivity.this);
                    mUI.uid = uid;
                    mUI.view.setZOrderOnTop(true);
                    mUserInfo.put(uid, mUI);
                    mSmallAdapter.update(getSmallVideoUser(mUserInfo, mBigUserId));
                    mRtcEngine.setupRemoteVideo(new VideoCanvas(mUI.view, Constants.RENDER_MODE_HIDDEN, uid));
                    setTranscoding();
                }
            });
        }

When user first starts the activity and joins the channel, then onJoinChannelSuccess is call and the first user is set up as mBigUserId which is added here (mUserInfo.put(mBigUserId, mUI);).

Since it is an interactive broadcast, when the second user joins, then onJoinChannelSuccess is called again and the second user is added as mBiguserId again. That doesn't seem right.

Moreover, when onUserJoined is called when the second interactive broadcaster joins, then the person enters in mSmallAdapter.

My question is: is onJoinChannelSuccess called when primary broadcaster enters broadcast as well as when other interactive broadcasters (or subbroadcasters) enter broadcast? Is onUserJoined called after onJoinChannelSuccess always when any user enters broadcast? The code only seems logical if onJoinChannelSuccess is only called once when primary user enter broadcasts and then only onUserJoined is called when secondary broadcasters enter broadcast without onJoinChannelSuccess  being called again. Please let me know if that is the case as it is most logical.

**Comment by plutoless** [comment]
onJoinChannelSuccess is your local callback when you join the channel. it has nothing to do with primary or secondary, it's up to you to put your own video into primary or not.
onUserJoined is remote callback for whoever broadcasters other than you joins the channel.

**Comment by lordmen99** [comment]
Hi, i need setup signaling server in my own server. where i can get the source code for that.

**Comment by AxesandGrinds** [comment]
> Hi, i need setup signaling server in my own server. where i can get the source code for that.

I had to create the signaling myself for my app. To have sufficient signaling for when users join as sub broadcasters to a channel is lengthy. I would advice you to use firebase messaging service and firebase cloud functions to create the signaling. 

Here's an example:

                     mRegistrationBroadcastReceiver = new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                Log.i("OnBroadcastReceiver", "received");

                if (intent.getAction().equals(Config.PUSH_NOTIFICATION)) {
                    Log.i("OnBroadcastReceiver", "push_received");

                    String click_action  = intent.getStringExtra("click_action");
                    channel              = intent.getStringExtra("channel");
                    callerID             = intent.getStringExtra("id");
                    callerName           = intent.getStringExtra("name");
                    callerUsername       = intent.getStringExtra("username");
                    callerImage          = intent.getStringExtra("image");

                    switch (click_action) {

                        case "com.app.ej.ms.TARGET_BROADCASTER_SESSION_STREAMER_INVITE":
                            // TODO For broadcaster, when broadcaster invites a streamer to sub video

                            Toasty.info(context, "You have invited " + callerUsername + " to join as a sub video streamer.", Toasty.LENGTH_LONG,true).show();

                            alert("You have invited " + callerUsername, "to join as a sub video streamer.");

                            break;

                        case "com.app.ej.ms.TARGET_STREAMER_BROADCASTER_SESSION_STREAMER_INVITE":
                            // TODO For streamer, when broadcaster invites a streamer to sub video

                            Toasty.info(context, "You have been invited to join this broadcast as a sub video streamer.", Toasty.LENGTH_LONG,true).show();

                            alert("You have been invited ", "to join this broadcast as a sub video streamer.");

                            break;
...

Then you have to create functions in the cloud with such click_actions. Then you have to create functions that save data to the cloud which will make cloud functions respond.

**Comment by AxesandGrinds** [comment]
> onJoinChannelSuccess is your local callback when you join the channel. it has nothing to do with primary or secondary, it's up to you to put your own video into primary or not.
> onUserJoined is remote callback for whoever broadcasters other than you joins the channel.

Okay, thanks!
