### ISSUE TITLE
"invalid_appid" why is that？

### ISSUE THREAD

**Issue by gugegev5** [AgoraIO/Advanced-Interactive-Broadcasting#35]
web live streaming
official demo
https://webdemo.agora.io/agora-web-showcase/examples/Agora-Interactive-Broadcasting-Live-Streaming-Web/?_ga=2.153837627.2049867682.1583225648-278061602.1582710435

code: 400
reason: "invalid_appid"
serverTs: 1583314607777
requestId: 4

**Comment by gugegev5** [comment]
rtmp://49.235.239.177:1935/stream/test

**Comment by cooljser** [comment]
I have the same problem. How can you solved it?

**Comment by plutoless** [comment]
看起来是appid没有填或者填的appid不对
